apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
           - alertmanager.monitoring.svc.cluster.local:9093

    rule_files:
      - rules.yaml

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        file_sd_configs:
          - files:
            - sd_node_exporter.yaml
      - job_name: 'api-server'
        file_sd_configs:
          - files:
            - sd_api_server.yaml

  rules.yaml: |-
    groups:
      - name: heartbeat
        rules:
        - alert: heartbeat
          expr: minute() % 2 == 1
          for: 30s


  sd_node_exporter.yaml: |-
    - targets:
      - 192.168.100.101:9100
      - 192.168.100.102:9100
      - 192.168.100.103:9100
      - 192.168.100.109:9100
      labels:
        system: "node-exporter"

  sd_api_server.yaml: |-
    - targets:
      - 192.168.100.101:10249
      - 192.168.100.102:10249
      - 192.168.100.103:10249
      labels:
        system: "api-server"