apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kibana-{{ .Release.Name }}
  name: kibana-lb-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana-{{ .Release.Name }}
  type: LoadBalancer

