apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: kibana-{{ .Release.Name }}
  name: kibana-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: "kibana"
  selector:
    matchLabels:
      app: kibana-{{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana-{{ .Release.Name }}
    spec:
      securityContext:
      containers:
      - image:  akitec/kibana-arm64:7.12.0
        name: kibana-{{ .Release.Name }}
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-{{ .Release.Name }}.monitoring.svc.cluster.local:9200