apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: "grafana"
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 472
      containers:
      - image: grafana/grafana
        name: {{ .Release.Name }}
        volumeMounts:
        - name: grafana-prometheus-configmap
          mountPath: "/etc/grafana/provisioning/datasources"
        - name: {{ .Release.Name }}-storage
          mountPath: /var/lib/grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin1234"
      volumes:
      - name: grafana-prometheus-configmap
        configMap:
          name: grafana-prometheus-datasource
      - name: {{ .Release.Name }}-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc