apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana-{{ .Release.Name }}
  name: grafana-lb-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-{{ .Release.Name }}
  type: LoadBalancer
