apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-{{ .Release.Name }}
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.100.109
    path: "/mnt/nfs/grafana"
