kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc-{{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard