apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-{{ .Release.Name }}
  name: prometheus-lb-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-{{ .Release.Name }}
  type: LoadBalancer
status:
  loadBalancer: {}
