apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-{{ .Release.Name }}
  name: prometheus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-{{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-{{ .Release.Name }}
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus-{{ .Release.Name }}
        volumeMounts:
        - name: prometheus-configmap
          mountPath: "/etc/prometheus/"
        ports:
          - containerPort: 9090
      volumes:
      - name: prometheus-configmap
        configMap:
          name: prometheus-cm-{{ .Release.Name }}
