apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch-{{ .Release.Name }}
  name: elasticsearch-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: "elasticseach"
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        name: elasticsearch-{{ .Release.Name }}
        volumeMounts:
        - name: elasticsearch-data-{{ .Release.Name }}
          mountPath: /data
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: api
        - containerPort: 9300
          name: gossip 
      tolerations:
      - key: app
        value: elasticsearch-{{ .Release.Name }}
        effect: NoSchedule
      volumes: 
      - name: elasticsearch-data-{{ .Release.Name }}
        persistentVolumeClaim:
          claimName: elasticsearch-pvc-{{ .Release.Name }}