kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-pvc-{{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard